# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# Bem vindo ao Heavynco.de

# Aqui estão as configurações do sites, elas estão no formato YAML é conhecido pela facilidade de leitura.
# As váriaveis globais para o projeto estão neste link https://jekyllrb.com/docs/variables/

name: Heavynco.de
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
css_folder: 'assets/stylesheets'
js_folder: 'assets/javascripts'
img_folder: 'assets/images'
include: ['.htaccess']
exclude: []
keep_files: ['.git','.svn']
